version: "3"

services:

  database:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"

  otree:
    # if using Docker Hub, leave "build: ./" commented out.
    # if you want to build an image locally, uncomment it.

    build: ./
    image: feele/ppdlior:1.0
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DATABASE}"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_PRODUCTION: ${OTREE_PRODUCTION}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
    ports:
      - ${OTREE_PORT}:80
    volumes:
      - "otree-resetdb:/opt/init"
    # Uncomment for live editing
      - ./:/opt/otree
    command: "otree runprodserver 0.0.0.0:80"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  database:
  otree-resetdb:

